PREFIX aaao: <https://ontology.swissartresearch.net/aaao/>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX lrmoo: <http://iflastandards.info/ns/lrm/lrmoo/>
PREFIX rdfschema: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX star: <https://r11.eu/ns/star/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX r11: <https://r11.eu/ns/spec/>
PREFIX r11pros: <https://r11.eu/ns/prosopography/>


SELECT
  ?G_seal_collection
    ?G_seal_collection_p_seal_collection_display_name
    ?G_seal_collection_g_seal_collection_seal_in_collection_assertion
    ?G_seal_collection_g_seal_collection_ownership_change

WHERE {

  ?G_seal_collection a crm:E78_Curated_Holding.
    ?G_seal_collection rdfschema:label ?G_seal_collection_p_seal_collection_display_name.

  OPTIONAL {
    ?G_seal_collection a crm:E78_Curated_Holding.
    ?G_seal_collection ^star:P140_crm_P46 ?G_seal_collection_g_seal_collection_seal_in_collection_assertion.
    ?G_seal_collection_g_seal_collection_seal_in_collection_assertion a star:E13_crm_P46.
  }

  OPTIONAL {
    ?G_seal_collection a crm:E78_Curated_Holding.
    ?G_seal_collection ^star:P141_crm_P24 ?G_seal_collection_0_g_seal_collection_ownership_change.
    ?G_seal_collection_0_g_seal_collection_ownership_change a star:E13_crm_P24.
    ?G_seal_collection_0_g_seal_collection_ownership_change star:P140_crm_P24 ?G_seal_collection_g_seal_collection_ownership_change.
    ?G_seal_collection_g_seal_collection_ownership_change a crm:E8_Acquisition.
  }

}