PREFIX aaao: <https://ontology.swissartresearch.net/aaao/>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX lrmoo: <http://iflastandards.info/ns/lrm/lrmoo/>
PREFIX rdfschema: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX star: <https://r11.eu/ns/star/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX r11: <https://r11.eu/ns/spec/>
PREFIX r11pros: <https://r11.eu/ns/prosopography/>


SELECT
  ?G_boulloterion
    ?G_boulloterion_p_boulloterion_display_name
    ?G_boulloterion_g_boulloterion_id_assignment
    ?G_boulloterion_g_boulloterion_produced_seal_assertion
    ?G_boulloterion_g_boulloterion_design_element_assertion
    ?G_boulloterion_g_boulloterion_ownership

WHERE {

  ?G_boulloterion a r11:Boulloterion.
    ?G_boulloterion rdfschema:label ?G_boulloterion_p_boulloterion_display_name.

  OPTIONAL {
    ?G_boulloterion a r11:Boulloterion.
    ?G_boulloterion ^crm:P140_assigned_attribute_to ?G_boulloterion_g_boulloterion_id_assignment.
    ?G_boulloterion_g_boulloterion_id_assignment a crm:E15_Identifier_Assignment.
  }

  OPTIONAL {
    ?G_boulloterion a r11:Boulloterion.
    ?G_boulloterion ^star:P140_spec_L1 ?G_boulloterion_g_boulloterion_produced_seal_assertion.
    ?G_boulloterion_g_boulloterion_produced_seal_assertion a star:E13_spec_L1.
  }

  OPTIONAL {
    ?G_boulloterion a r11:Boulloterion.
    ?G_boulloterion ^star:P140_crm_P65 ?G_boulloterion_g_boulloterion_design_element_assertion.
    ?G_boulloterion_g_boulloterion_design_element_assertion a star:E13_crm_P65.
  }
    ?G_boulloterion a r11:Boulloterion.
    ?G_boulloterion ^star:P141_crm_P24 ?G_boulloterion_0_g_boulloterion_ownership.
    ?G_boulloterion_0_g_boulloterion_ownership a star:E13_crm_P24.
    ?G_boulloterion_0_g_boulloterion_ownership star:P140_crm_P24 ?G_boulloterion_g_boulloterion_ownership.
    ?G_boulloterion_g_boulloterion_ownership a crm:E8_Acquisition.

}