PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX lrmoo: <http://iflastandards.info/ns/lrm/lrmoo/>
PREFIX star: <https://r11.eu/ns/star/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX r11: <https://r11.eu/ns/spec/>
PREFIX r11pros: <https://r11.eu/ns/prosopography/>

SELECT
?written_work
  ?written_work__written_work_label
  ?written_work__work_creation_assertion

WHERE {
?written_work a r11:Text_Expression.

  ?written_work crm:P3_has_note ?written_work__written_work_label.

  OPTIONAL {
  ?written_work__work_creation_assertion a star:E13_lrmoo_R17.
  ?written_work ^crm:P141_assigned ?written_work__work_creation_assertion.
  }
}

