PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX lrmoo: <http://iflastandards.info/ns/lrm/lrmoo/>
PREFIX star: <https://r11.eu/ns/star/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX r11: <https://r11.eu/ns/spec/>
PREFIX r11pros: <https://r11.eu/ns/prosopography/>

SELECT
?person
  ?person__person_id_assignment
  ?person__person_appellation_assertion
    ?person__person_appellation_assertion__person_appellation_is
  ?person__person_gender_assertion
  ?person__person_ethnicity_assertion
  ?person__person_descriptive_name
  ?person__person_possession_assertion
  ?person__person_status_assertion
  ?person__person_religion_assertion
  ?person__person_occupation_assertion
  ?person__person_language_assertion
  ?person__person_kinship_assertion
  ?person__birth_circumstances_claim
  ?person__person_death_assertion

WHERE {
?person a crm:E21_Person.

  OPTIONAL {
  ?person__person_id_assignment a crm:E15_Identifier_Assignment.
  ?person ^crm:P140_assigned_attribute_to ?person__person_id_assignment.
  }

  OPTIONAL {
  ?person__person_appellation_assertion a star:E13_crm_P1.
  ?person ^crm:P140_assigned_attribute_to ?person__person_appellation_assertion.
  
    ?person__person_appellation_assertion crm:P141_assigned ?person__person_appellation_assertion___pai.
    ?person__person_appellation_assertion___pai crm:P190_has_symbolic_content ?person__person_appellation_assertion__person_appellation_is.
  }

  OPTIONAL {
  ?person__person_gender_assertion a star:E13_crm_P41.
  ?person ^crm:P141_assigned ?person__person_gender_assertion.
  }

  OPTIONAL {
  ?person__person_ethnicity_assertion a star:E13_crm_P107.
  ?person ^crm:P141_assigned ?person__person_ethnicity_assertion.
  }

  OPTIONAL {
  ?person crm:P3_has_note ?person__person_descriptive_name.
  }

  OPTIONAL {
  ?person__person_possession_assertion a star:E13_crm_P51.
  ?person ^crm:P141_assigned ?person__person_possession_assertion.
  }

  OPTIONAL {
  ?person__person_status_assertion a star:E13_sdhss_P26.
  ?person ^crm:P141_assigned ?person__person_status_assertion.
  }

  OPTIONAL {
  ?person__person_religion_assertion a star:E13_sdhss_P36.
  ?person ^crm:P141_assigned ?person__person_religion_assertion.
  }

  OPTIONAL {
  ?person__person_occupation_assertion a star:E13_sdhss_P13.
  ?person ^crm:P141_assigned ?person__person_occupation_assertion.
  }

  OPTIONAL {
  ?person__person_language_assertion a star:E13_sdhss_P38.
  ?person ^crm:P140_assigned_attribute_to ?person__person_language_assertion.
  }

  OPTIONAL {
  ?person__person_kinship_assertion a star:E13_sdhss_P17.
  ?person ^crm:P141_assigned ?person__person_kinship_assertion.
  }

  ?person__birth_circumstances_claim a star:E13_crm_P98.
  ?person ^crm:P141_assigned ?person__birth_circumstances_claim.

  ?person__person_death_assertion a star:E13_crm_P100.
  ?person ^crm:P141_assigned ?person__person_death_assertion.
}

