PREFIX aaao: <https://ontology.swissartresearch.net/aaao/>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX lrmoo: <http://iflastandards.info/ns/lrm/lrmoo/>
PREFIX rdfschema: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX star: <https://r11.eu/ns/star/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX r11: <https://r11.eu/ns/spec/>
PREFIX r11pros: <https://r11.eu/ns/prosopography/>


SELECT
  ?G_written_text
    ?G_written_text_p_written_text_display_name
    ?G_written_text_g_written_text_title_assertion
    ?G_written_text_g_written_text_creation
    ?G_written_text_g_written_text_published_as_assertion
    ?G_written_text_g_written_text_written_in_assertion
    ?G_written_text_g_written_text_version_of_assertion

WHERE {

  ?G_written_text a r11:Text_Expression.
    ?G_written_text rdfschema:label ?G_written_text_p_written_text_display_name.

  OPTIONAL {
    ?G_written_text a r11:Text_Expression.
    ?G_written_text ^star:P140_crm_P1 ?G_written_text_g_written_text_title_assertion.
    ?G_written_text_g_written_text_title_assertion a star:E13_crm_P1.
  }
    ?G_written_text a r11:Text_Expression.
    ?G_written_text ^star:P141_lrmoo_R17 ?G_written_text_0_g_written_text_creation.
    ?G_written_text_0_g_written_text_creation a star:E13_lrmoo_R17.
    ?G_written_text_0_g_written_text_creation star:P140_lrmoo_R17 ?G_written_text_g_written_text_creation.
    ?G_written_text_g_written_text_creation a lrmoo:F28_Expression_Creation.

  OPTIONAL {
    ?G_written_text a r11:Text_Expression.
    ?G_written_text ^star:P141_crm_P165 ?G_written_text_g_written_text_published_as_assertion.
    ?G_written_text_g_written_text_published_as_assertion a star:E13_crm_P165.
  }

  OPTIONAL {
    ?G_written_text a r11:Text_Expression.
    ?G_written_text ^star:P141_crm_P128 ?G_written_text_g_written_text_written_in_assertion.
    ?G_written_text_g_written_text_written_in_assertion a star:E13_crm_P128.
  }

  OPTIONAL {
    ?G_written_text a r11:Text_Expression.
    ?G_written_text ^star:P141_lrmoo_R3 ?G_written_text_g_written_text_version_of_assertion.
    ?G_written_text_g_written_text_version_of_assertion a star:E13_lrmoo_R3.
  }

}