PREFIX aaao: <https://ontology.swissartresearch.net/aaao/>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX lrmoo: <http://iflastandards.info/ns/lrm/lrmoo/>
PREFIX rdfschema: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX star: <https://r11.eu/ns/star/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX r11: <https://r11.eu/ns/spec/>
PREFIX r11pros: <https://r11.eu/ns/prosopography/>


SELECT
  ?G_social_relationship
    ?G_social_relationship_p_social_relationship_display_name
    ?G_social_relationship_g_social_relationship_categorisation_assertion

WHERE {

  ?G_social_relationship a r11pros:C4.
    ?G_social_relationship rdfschema:label ?G_social_relationship_p_social_relationship_display_name.

  OPTIONAL {
    ?G_social_relationship a r11pros:C4.
    ?G_social_relationship ^crm:P41_classified ?G_social_relationship_g_social_relationship_categorisation_assertion.
    ?G_social_relationship_g_social_relationship_categorisation_assertion a crm:E17_Type_Assignment.
  }

}