PREFIX aaao: <https://ontology.swissartresearch.net/aaao/>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX lrmoo: <http://iflastandards.info/ns/lrm/lrmoo/>
PREFIX rdfschema: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX star: <https://r11.eu/ns/star/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX r11: <https://r11.eu/ns/spec/>
PREFIX r11pros: <https://r11.eu/ns/prosopography/>


SELECT
  ?G_passage
    ?G_passage_p_passage_reference_string
    ?G_passage_p_passage_content
    ?G_passage_g_passage_in_publication_assertion
    ?G_passage_g_passage_on_object_assertion
    ?G_passage_g_passage_on_boulloterion_assertion

WHERE {

  ?G_passage a crm:E33_Linguistic_Object.
    ?G_passage rdfschema:label ?G_passage_p_passage_reference_string.
    ?G_passage crm:P190_has_symbolic_content ?G_passage_p_passage_content.

  OPTIONAL {
    ?G_passage a crm:E33_Linguistic_Object.
    ?G_passage ^star:P140_lrmoo_R15 ?G_passage_g_passage_in_publication_assertion.
    ?G_passage_g_passage_in_publication_assertion a star:E13_lrmoo_R15.
  }

  OPTIONAL {
    ?G_passage a crm:E33_Linguistic_Object.
    ?G_passage ^star:P141_crm_P128 ?G_passage_g_passage_on_object_assertion.
    ?G_passage_g_passage_on_object_assertion a star:E13_crm_P128.
  }

  OPTIONAL {
    ?G_passage a crm:E33_Linguistic_Object.
    ?G_passage ^star:P141_crm_P128 ?G_passage_g_passage_on_boulloterion_assertion.
    ?G_passage_g_passage_on_boulloterion_assertion a star:E13_crm_P128.
  }

}