PREFIX aaao: <https://ontology.swissartresearch.net/aaao/>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX lrmoo: <http://iflastandards.info/ns/lrm/lrmoo/>
PREFIX rdfschema: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX star: <https://r11.eu/ns/star/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX r11: <https://r11.eu/ns/spec/>
PREFIX r11pros: <https://r11.eu/ns/prosopography/>


SELECT
  ?G_author_group
    ?G_author_group_p_author_group_display_name
    ?G_author_group_g_author_group_member_assertion

WHERE {

  ?G_author_group a r11:Author_Group.
    ?G_author_group rdfschema:label ?G_author_group_p_author_group_display_name.

  OPTIONAL {
    ?G_author_group a r11:Author_Group.
    ?G_author_group ^star:P140_crm_P107 ?G_author_group_g_author_group_member_assertion.
    ?G_author_group_g_author_group_member_assertion a star:E13_crm_P107.
  }

}