PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX lrmoo: <http://iflastandards.info/ns/lrm/lrmoo/>
PREFIX star: <https://r11.eu/ns/star/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX r11: <https://r11.eu/ns/spec/>
PREFIX r11pros: <https://r11.eu/ns/prosopography/>

SELECT
?_person_stub__person
  ?_person_stub__person__person_descriptive_name

WHERE {
?_person_stub__person a crm:E21_Person.

  OPTIONAL {
  ?_person_stub__person crm:P3_has_note ?_person_stub__person__person_descriptive_name.
  }
}

