PREFIX aaao: <https://ontology.swissartresearch.net/aaao/>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX lrmoo: <http://iflastandards.info/ns/lrm/lrmoo/>
PREFIX rdfschema: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX star: <https://r11.eu/ns/star/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX r11: <https://r11.eu/ns/spec/>
PREFIX r11pros: <https://r11.eu/ns/prosopography/>


SELECT
  ?G_publication
    ?G_publication_p_publication_display_name
    ?G_publication_g_publication_creation
    ?G_publication_g_publication_derived_from_assertion

WHERE {

  ?G_publication a r11:Publication.
    ?G_publication rdfschema:label ?G_publication_p_publication_display_name.
    ?G_publication a r11:Publication.
    ?G_publication ^star:P141_lrmoo_R17 ?G_publication_0_g_publication_creation.
    ?G_publication_0_g_publication_creation a star:E13_lrmoo_R17.
    ?G_publication_0_g_publication_creation star:P140_lrmoo_R17 ?G_publication_g_publication_creation.
    ?G_publication_g_publication_creation a lrmoo:F28_Expression_Creation.

  OPTIONAL {
    ?G_publication a r11:Publication.
    ?G_publication ^star:P140_lrmoo_R76 ?G_publication_g_publication_derived_from_assertion.
    ?G_publication_g_publication_derived_from_assertion a star:E13_lrmoo_R76.
  }

}