PREFIX aaao: <https://ontology.swissartresearch.net/aaao/>
PREFIX crm: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX lrmoo: <http://iflastandards.info/ns/lrm/lrmoo/>
PREFIX rdfschema: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX star: <https://r11.eu/ns/star/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX r11: <https://r11.eu/ns/spec/>
PREFIX r11pros: <https://r11.eu/ns/prosopography/>


SELECT
  ?G_language
    ?G_language_p_language_display_name

WHERE {

  ?G_language a r11pros:C29.
    ?G_language rdfschema:label ?G_language_p_language_display_name.

}